######################################################################
# Automatically generated by qmake (3.0) ?? 7? 4 09:49:39 2016
######################################################################

TEMPLATE = app
TARGET = design
INCLUDEPATH += .

# Input
FORMS += design.ui
